name: 'Write Version To File'
description: 'Writes version information to a structured JSON file and commits the file'
inputs:
  version:
    description: The version number to use
    required: true
  path:
    description: The path to the version file to output
    required: true
  user-email:
    description: The email of the user that commits the version file
    required: false
    default: 'build@dolittle.com'
  user-name:
    description: The name of the user that commits the version file
    required: false
    default: 'dolittle-build'
 
runs:
  using: 'node12'
  main: 'release/index.js'